### ISSUE TITLE
Implement socet splitting

### ISSUE THREAD

**Issue by countradooku** [nurmohammed840/websocket.rs#10]
I would really appreciate that you could implement socket splitting similar to here https://github.com/denoland/fastwebsockets/blob/main/examples/echo_server_split.rs

**Comment by nurmohammed840** [comment]
Unlike [fastwebsockets](https://docs.rs/fastwebsockets/latest/fastwebsockets/upgrade/struct.UpgradeFut.html) It does not rely on any specific runtime, so there is nothing to split.

However, you can split a WebSocket like this:

```rust
let (reader, writer) = tokio::io::split(stream);

let ws_reader = WebSocket::client(reader);
let ws_writer = WebSocket::client(writer);
```
