### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by ghost** [nurmohammed840/websocket.rs#5]
without TLS support made the high performance useless.

**Comment by nurmohammed840** [comment]
I remove TLS support and http websocket handshake 

I think we should create a separate crate instead, which provides this functionality.

**Comment by TroyKomodo** [comment]
I think, @0xCuteSocks what the author of this crate is trying to say is:
Usually websockets sit ontop of http which sit on top of some TLS enabled transport be it TCP with SSL or QUIC.
The stack looks like

WS -> HTTP -> SSL -> TCP

This library seems to implement the WS part of that stack. However there are 0 examples of it working with any of the most commonly used HTTP libraries in Rust, which essentially renders this crate useless.

**Comment by TroyKomodo** [comment]
It seems that, this crate does exactly that https://github.com/denoland/fastwebsockets as well. But also provides some examples on how to implement http upgrades.

**Comment by nurmohammed840** [comment]
There should not be any issues if you are using a http library or framework.

But for others, All missing pieces are already written, The example directory contains the [protocol handshake](https://github.com/nurmohammed840/websocket.rs/blob/main/examples/utils/handshake.rs) related code. And you can use [tokio-rustls](https://github.com/rustls/tokio-rustls) for transport layer security.
