### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by countradooku** [nurmohammed840/websocket.rs#6]
Is this package still maintained? And if it if can you give an example usage with axum for example?

**Comment by nurmohammed840** [comment]
You can create [WebSocket](https://docs.rs/web-socket/latest/web_socket/struct.WebSocket.html) instance from anything that implement [AsyncRead](https://docs.rs/tokio/latest/tokio/io/trait.AsyncRead.html) or [AsyncWrite](https://docs.rs/tokio/latest/tokio/io/trait.AsyncWrite.html)

>Can you give an example usage with `axum` for example?

I will consider adding some examples with other http frameworks
