### ISSUE TITLE
Error: reserve bit must be `0`

### ISSUE THREAD

**Issue by wbogocki** [nurmohammed840/websocket.rs#7]
I'm getting this error on a call to `.recv()`. I'm not familiar with the WS specification to figure out what's causing it.

**Comment by nurmohammed840** [comment]
https://github.com/nurmohammed840/websocket.rs/blob/0727252cd0f1b8df75943dadbaeeb55f0f38c653/src/ws.rs#L201-L207

Currently it doesn't support any [extensions](https://datatracker.ietf.org/doc/html/rfc6455#section-9). For example [permessage-deflect](https://datatracker.ietf.org/doc/html/rfc7692)

Although extensions are negotiated (and could be ignored), But it is more convenient to fail the connection if an unknown extension is received by the server.

So, when trying to connect from client, you shouldn't set any extension.

**Comment by wbogocki** [comment]
Yes. There are no extensions.

There's some weirdness here. This error happens depending on how/where I await/poll the future. I'm investigating right now (or walking blind depending on how you look at it).

**Comment by nurmohammed840** [comment]
Hm, interesting, Is there any way to reproduced this.

there is also a possibility, the stream is consuming or failed to deliver expected WebSocket frame ?

**Comment by wbogocki** [comment]
I don't know. I will see if I can isolate it. So far managed to induce a `payload too large` (once, doesn't replicate) and `early eof`.

I'm very interested if it's something in the library or my code (I would be surprised if it's the latter, it's a fairly new codebase, no unsafe etc. etc.)

**Comment by nurmohammed840** [comment]
A misbehaved stream could be an error. which may cause the application to receive faulty frames.

**Comment by wbogocki** [comment]
Do you mean that the AsyncRead/AsyncWrite implementer may be wrong or that the server is wrong?

The latter can be excluded. It serves a lot of people and works in another library. The former... it's just a:

```rust
pub type TlsWs = WebSocket<TlsStream<BufReader<TcpStream>>>;
```

All standard types.

edit. `TlsStream` is from `tokio_rustls`. The rest are from `tokio`.

**Comment by nurmohammed840** [comment]
Its just an possibility that could may a reason,

But in this case, I suspect that there may be some data left over from the HTTP protocol ? or http parser consuming some WebSocket frame data ?

which may be the main culprit.

**Comment by wbogocki** [comment]
Yes, I welcome the ideas.

The HTTP upgrade succeeds, I receive a few thousand (eyeballing) messages before the error happens.

**Comment by nurmohammed840** [comment]
I suggest you to use any http parser or framework (like axum).

Here is an [example](https://github.com/nurmohammed840/websocket.rs/tree/main/examples/axum-example) with axum.

**Comment by wbogocki** [comment]
It won't be a solution. I'm not trying to get from A to B (at least not in the way you probably think). I'm trying to understand what is going on.

The problem is not in this library. I just (1) made a naive one-file program that connects to the same stream - which works. I also (2) ported everything to `fastwebsockets` as a trial to see if the library is at fault and got a `WebSocket(ReservedBitsNotZero)`.

Sorry for taking your time. This can be closed.

By chance, do you have any ideas why the former of these two may give an error?

(1) This works:
```rust
let mut stream_map = StreamMap::new();

for _ in 0..10 {
    let s: TheStream  connect(...);
    let s = Box::pin(futures::stream::try_unfold(s, |mut s| async {
        Ok(Some((s.recv().await?, s)))
    }))
    stream_map.insert(i, s);
}

loop {
    stream_map.next().await().unwrap(); // works
}
```

(2) This fails:
```rust
let mut stream_map = StreamMap::new();

for _ in 0..10 {
    let s: TheStream = connect(...);
    stream_map.insert(i, s);
}

loop {
    stream_map.next().await().unwrap(); // eventually fails
}

impl futures::Stream for TheStream {
    type Item = LinkResult<TheEvent>;

    fn poll_next(mut self: Pin<&mut Self>, cx: &mut task::Context<'_>) -> Poll<Option<Self::Item>> {
        let f = self.recv();
        pin_mut!(f);
        f.poll(cx).map(Some)
    }
}
```

**Comment by nurmohammed840** [comment]
> do you have any ideas why the former of these two may give an error ?

It is difficult to pinpoint the cause of the problem without full context.
It would be helpful, if I could run something locally.

**Comment by wbogocki** [comment]
It's alright, I've solved it. I had been misunderstanding Rust syntax and ended up creating many recv() futures at the same time. Thanks for the help.
