### ISSUE TITLE
Store sockets

### ISSUE THREAD

**Issue by 0spura** [nurmohammed840/websocket.rs#8]
Hello! Is there an efficient way to save connected sockets?
I'm trying to use ws in dispatch handler ([my code](https://github.com/dynbox/hortalink/blob/dev/websocket/src/app.rs#L78)) but I only can use the reference, it's hard to store reference, if I use Arc with Mutex, I can't use close functions because of move. I'm saving in this form ([my code](https://github.com/dynbox/hortalink/blob/f5501e753222ddc66b56bad9f54fab6f1c9ecd19/websocket/src/handlers/mod.rs#L32)).

**Comment by nurmohammed840** [comment]
> I'm trying to use ws in dispatch handler ([my code](https://github.com/dynbox/hortalink/blob/dev/websocket/src/app.rs#L78)) but I only can use the reference, it's hard to store reference

operation like [send()](https://docs.rs/web-socket/latest/web_socket/struct.WebSocket.html#method.send), [recv()](https://docs.rs/web-socket/latest/web_socket/struct.WebSocket.html#method.recv) require exclusive reference `&mut WebSocket<..>` not `&WebSocket<..>`

> if I use Arc with Mutex.

Avoid shared reference, Its just create new problems.
Try different architecture (for example [Actor model](https://en.wikipedia.org/wiki/Actor_model))

 >  I can't use close functions because of move.

`close()` accept `self` and not `&mut self`.
The reason for this design is that after sending a close frame the endpoint no longer communicates.

However you can [send raw close frame](https://github.com/nurmohammed840/websocket.rs/blob/0727252cd0f1b8df75943dadbaeeb55f0f38c653/src/ws.rs#L80C1-L85C17) anyway:

```rust
use web_socket::{CloseReason, Frame};

ws.send_raw(Frame {
   fin: true,
   opcode: 8,
   data: CloseReason::to_bytes(<reason>).as_ref()
})
.await?;
```

**Comment by 0spura** [comment]
Got it, thanks for your help, I'll see if I can store the sockets like you said

**Comment by 0spura** [comment]
I found some examples, now it's much clearer, thanks for the recommendation

**Comment by 0spura** [comment]
@nurmohammed840 I found [actor from actix](https://github.com/actix/actix), it's possible to implement using web-socket? I can't find any example without actix-web-actors

**Comment by nurmohammed840** [comment]
actor is a model of concurrent architecture.

I like to think actor as a thread (task, coroutine, etc...) who communicate (using massage passing system) with other actor (thread) via channels.

Its nothing to do with [actix](https://github.com/actix/actix), 

When I am free, I will add an example of actor model by building a chat application.

**Comment by 0spura** [comment]
If you're too busy, can you give me some dependencies or examples so I can get started? @nurmohammed840

**Comment by nurmohammed840** [comment]
Lets see, I will find some time to write some examples. 

But  [here is a demonstration](https://www.youtube.com/watch?v=fTXuGRP1ee4&ab_channel=RustLabConference) by [Alice Ryhl](https://github.com/Darksonn)

**Comment by nurmohammed840** [comment]
@baskerbyte, Thanks for your patience,

[Here is a chat example](https://github.com/nurmohammed840/websocket.rs/blob/main/examples/chatroom.rs) using [actor model](https://en.wikipedia.org/wiki/Actor_model)
